name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        node-version: ['18', '20', '22']
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Cache Node Modules
      uses: actions/cache@v4
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install
      run: yarn install --frozen-lockfile

    - name: Build (ubuntu)
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: yarn

    - name: Build (macos)
      if: ${{ matrix.os == 'macos-latest' }}
      run: CURRENT_ARCH=arm64 yarn

    - name: Test
      run: yarn test
